In [1]:
import matminer

In [42]:
from matminer.datasets import get_available_datasets
get_available_datasets()

boltztrap_mp: Effective mass and thermoelectric properties of 8924 compounds in The  Materials Project database that are calculated by the BoltzTraP software package run on the GGA-PBE or GGA+U density functional theory calculation results. The properties are reported at the temperature of 300 Kelvin and the carrier concentration of 1e18 1/cm3.

brgoch_superhard_training: 2574 materials used for training regressors that predict shear and bulk modulus.

castelli_perovskites: 18,928 perovskites generated with ABX combinatorics, calculating gllbsc band gap and pbe structure, and also reporting absolute band edge positions and heat of formation.

citrine_thermal_conductivity: Thermal conductivity of 872 compounds measured experimentally and retrieved from Citrine database from various references. The reported values are measured at various temperatures of which 295 are at room temperature.

dielectric_constant: 1,056 structures with dielectric properties, calculated with DFPT-PBE.

double_perovskites_gap: Band gap of 1306 double perovskites (a_1-b_1-a_2-b_2-O6) calculated using ﻿Gritsenko, van Leeuwen, van Lenthe and Baerends potential (gllbsc) in GPAW.

double_perovskites_gap_lumo: Supplementary lumo data of 55 atoms for the double_perovskites_gap dataset.

elastic_tensor_2015: 1,181 structures with elastic properties calculated with DFT-PBE.

expt_formation_enthalpy: Experimental formation enthalpies for inorganic compounds, collected from years of calorimetric experiments. There are 1,276 entries in this dataset, mostly binary compounds. Matching mpids or oqmdids as well as the DFT-computed formation energies are also added (if any).

expt_formation_enthalpy_kingsbury: Dataset containing experimental standard formation enthalpies for solids. Formation enthalpies were compiled primarily from Kim et al., Kubaschewski, and the NIST JANAF tables (see references). Elements, liquids, and gases were excluded. Data were deduplicated such that each material is associated with a single formation enthalpy value. Refer to Wang et al. (see references) for a complete desciption of the methods used. Materials Project database IDs (mp-ids) were assigned to materials from among computed materials in the Materials Project database (version 2021.03.22) that were 1) not marked 'theoretical', 2) had structures matching at least one ICSD material, and 3) were within 200 meV of the DFT-computed stable energy hull (e_above_hull < 0.2 eV). Among these candidates, we chose the mp-id with the lowest e_above_hull that matched the reported spacegroup (where available).

expt_gap: Experimental band gap of 6354 inorganic semiconductors.

expt_gap_kingsbury: Identical to the matbench_expt_gap dataset, except that Materials Project database IDs (mp-ids) have been associated with each material using the same method as described for the expt_formation_enthalpy_kingsbury dataset. Columns have also been renamed for consistency with the formation enthalpy data.

flla: 3938 structures and computed formation energies from "Crystal Structure Representations for Machine Learning Models of Formation Energies."

glass_binary: Metallic glass formation data for binary alloys, collected from various experimental techniques such as melt-spinning or mechanical alloying. This dataset covers all compositions with an interval of 5 at. % in 59 binary systems, containing a total of 5959 alloys in the dataset. The target property of this dataset is the glass forming ability (GFA), i.e. whether the composition can form monolithic glass or not, which is either 1 for glass forming or 0 for non-full glass forming.

glass_binary_v2: Identical to glass_binary dataset, but with duplicate entries merged. If there was a disagreement in gfa when merging the class was defaulted to 1.

glass_ternary_hipt: Metallic glass formation dataset for ternary alloys, collected from the high-throughput sputtering experiments measuring whether it is possible to form a glass using sputtering. The hipt experimental data are of the Co-Fe-Zr, Co-Ti-Zr, Co-V-Zr and Fe-Ti-Nb ternary systems.

glass_ternary_landolt: Metallic glass formation dataset for ternary alloys, collected from the "Nonequilibrium Phase Diagrams of Ternary Amorphous Alloys,’ a volume of the Landolt– Börnstein collection. This dataset contains experimental measurements of whether it is possible to form a glass using a variety of processing techniques at thousands of compositions from hundreds of ternary systems. The processing techniques are designated in the "processing" column. There are originally 7191 experiments in this dataset, will be reduced to 6203 after deduplicated, and will be further reduced to 6118 if combining multiple data for one composition. There are originally 6780 melt-spinning experiments in this dataset, will be reduced to 5800 if deduplicated, and will be further reduced to 5736 if combining multiple experimental data for one composition.

heusler_magnetic: 1153 Heusler alloys with DFT-calculated magnetic and electronic properties. The 1153 alloys include 576 full, 449 half and 128 inverse Heusler alloys. The data are extracted and cleaned (including de-duplicating) from Citrine.

jarvis_dft_2d: Various properties of 636 2D materials computed with the OptB88vdW and TBmBJ functionals taken from the JARVIS DFT database.

jarvis_dft_3d: Various properties of 25,923 bulk materials computed with the OptB88vdW and TBmBJ functionals taken from the JARVIS DFT database.

jarvis_ml_dft_training: Various properties of 24,759 bulk and 2D materials computed with the OptB88vdW and TBmBJ functionals taken from the JARVIS DFT database.

m2ax: Elastic properties of 223 stable M2AX compounds from "A comprehensive survey of M2AX phase elastic properties" by Cover et al. Calculations are PAW PW91.

matbench_dielectric: Matbench v0.1 test dataset for predicting refractive index from structure. Adapted from Materials Project database. Removed entries having a formation energy (or energy above the convex hull) more than 150meV and those having refractive indices less than 1 and those containing noble gases. Retrieved April 2, 2019. For benchmarking w/ nested cross validation, the order of the dataset must be identical to the retrieved data; refer to the Automatminer/Matbench publication for more details.

matbench_expt_gap: Matbench v0.1 test dataset for predicting experimental band gap from composition alone. Retrieved from Zhuo et al. supplementary information. Deduplicated according to composition, removing compositions with reported band gaps spanning more than a 0.1eV range; remaining compositions were assigned values based on the closest experimental value to the mean experimental value for that composition among all reports. For benchmarking w/ nested cross validation, the order of the dataset must be identical to the retrieved data; refer to the Automatminer/Matbench publication for more details.

matbench_expt_is_metal: Matbench v0.1 test dataset for classifying metallicity from composition alone. Retrieved from Zhuo et al. supplementary information. Deduplicated according to composition, ensuring no conflicting reports were entered for any compositions (i.e., no reported compositions were both metal and nonmetal). For benchmarking w/ nested cross validation, the order of the dataset must be identical to the retrieved data; refer to the Automatminer/Matbench publication for more details.

matbench_glass: Matbench v0.1 test dataset for predicting full bulk metallic glass formation ability from chemical formula. Retrieved from "Nonequilibrium Phase Diagrams of Ternary Amorphous Alloys,’ a volume of the Landolt– Börnstein collection. Deduplicated according to composition, ensuring no compositions were reported as both GFA and not GFA (i.e., all reports agreed on the classification designation). For benchmarking w/ nested cross validation, the order of the dataset must be identical to the retrieved data; refer to the Automatminer/Matbench publication for more details.

matbench_jdft2d: Matbench v0.1 test dataset for predicting exfoliation energies from crystal structure (computed with the OptB88vdW and TBmBJ functionals). Adapted from the JARVIS DFT database. For benchmarking w/ nested cross validation, the order of the dataset must be identical to the retrieved data; refer to the Automatminer/Matbench publication for more details.

matbench_log_gvrh: Matbench v0.1 test dataset for predicting DFT log10 VRH-average shear modulus from structure. Adapted from Materials Project database. Removed entries having a formation energy (or energy above the convex hull) more than 150meV and those having negative G_Voigt, G_Reuss, G_VRH, K_Voigt, K_Reuss, or K_VRH and those failing G_Reuss <= G_VRH <= G_Voigt or K_Reuss <= K_VRH <= K_Voigt and those containing noble gases. Retrieved April 2, 2019. For benchmarking w/ nested cross validation, the order of the dataset must be identical to the retrieved data; refer to the Automatminer/Matbench publication for more details.

matbench_log_kvrh: Matbench v0.1 test dataset for predicting DFT log10 VRH-average bulk modulus from structure. Adapted from Materials Project database. Removed entries having a formation energy (or energy above the convex hull) more than 150meV and those having negative G_Voigt, G_Reuss, G_VRH, K_Voigt, K_Reuss, or K_VRH and those failing G_Reuss <= G_VRH <= G_Voigt or K_Reuss <= K_VRH <= K_Voigt and those containing noble gases. Retrieved April 2, 2019. For benchmarking w/ nested cross validation, the order of the dataset must be identical to the retrieved data; refer to the Automatminer/Matbench publication for more details.

matbench_mp_e_form: Matbench v0.1 test dataset for predicting DFT formation energy from structure. Adapted from Materials Project database. Removed entries having formation energy more than 2.5eV and those containing noble gases. Retrieved April 2, 2019. For benchmarking w/ nested cross validation, the order of the dataset must be identical to the retrieved data; refer to the Automatminer/Matbench publication for more details.

matbench_mp_gap: Matbench v0.1 test dataset for predicting DFT PBE band gap from structure. Adapted from Materials Project database. Removed entries having a formation energy (or energy above the convex hull) more than 150meV and those containing noble gases. Retrieved April 2, 2019. For benchmarking w/ nested cross validation, the order of the dataset must be identical to the retrieved data; refer to the Automatminer/Matbench publication for more details.

matbench_mp_is_metal: Matbench v0.1 test dataset for predicting DFT metallicity from structure. Adapted from Materials Project database. Removed entries having a formation energy (or energy above the convex hull) more than 150meV and those containing noble gases. Retrieved April 2, 2019. For benchmarking w/ nested cross validation, the order of the dataset must be identical to the retrieved data; refer to the Automatminer/Matbench publication for more details.

matbench_perovskites: Matbench v0.1 test dataset for predicting formation energy from crystal structure. Adapted from an original dataset generated by Castelli et al. For benchmarking w/ nested cross validation, the order of the dataset must be identical to the retrieved data; refer to the Automatminer/Matbench publication for more details.

matbench_phonons: Matbench v0.1 test dataset for predicting vibration properties from crystal structure. Original data retrieved from Petretto et al. Original calculations done via ABINIT in the harmonic approximation based on density functional perturbation theory. Removed entries having a formation energy (or energy above the convex hull) more than 150meV. For benchmarking w/ nested cross validation, the order of the dataset must be identical to the retrieved data; refer to the Automatminer/Matbench publication for more details.

matbench_steels: Matbench v0.1 test dataset for predicting steel yield strengths from chemical composition alone. Retrieved from Citrine informatics. Deduplicated. For benchmarking w/ nested cross validation, the order of the dataset must be identical to the retrieved data; refer to the Automatminer/Matbench publication for more details.

mp_all_20181018: A complete copy of the Materials Project database as of 10/18/2018. mp_all files contain structure data for each material while mp_nostruct does not.

mp_nostruct_20181018: A complete copy of the Materials Project database as of 10/18/2018. mp_all files contain structure data for each material while mp_nostruct does not.

phonon_dielectric_mp: Phonon (lattice/atoms vibrations) and dielectric properties of 1296 compounds computed via ABINIT software package in the harmonic approximation based on density functional perturbation theory.

piezoelectric_tensor: 941 structures with piezoelectric properties, calculated with DFT-PBE.

ricci_boltztrap_mp_tabular: Ab-initio electronic transport database for inorganic materials. Complex multivariable BoltzTraP simulation data is condensed down into tabular form of two main motifs: average eigenvalues at set moderate carrier concentrations and temperatures, and optimal values among all carrier concentrations and temperatures within certain ranges. Here are reported the average of the eigenvalues of conductivity effective mass (mₑᶜᵒⁿᵈ), the Seebeck coefficient (S), the conductivity (σ), the electronic thermal conductivity (κₑ), and the Power Factor (PF) at a doping level of 10¹⁸ cm⁻³ and at a temperature of 300 K for n- and p-type. Also, the maximum values for S, σ, PF, and the minimum value for κₑ chosen among the temperatures [100, 1300] K, the doping levels [10¹⁶, 10²¹] cm⁻³, and doping types are reported. The properties that depend on the relaxation time are reported divided by the constant value 10⁻¹⁴. The average of the eigenvalues for all the properties at all the temperatures, doping levels, and doping types are reported in the tables for each entry. Data is indexed by materials project id (mpid)

steel_strength: 312 steels with experimental yield strength and ultimate tensile strength, extracted and cleaned (including de-duplicating) from Citrine.

superconductivity2018: Dataset of ~16,000 experimental superconductivity records (critical temperatures) from Stanev et al., originally from the Japanese National Institute for Materials Science. Does not include structural data. Includes ~300 measurements from materials found without superconductivity (Tc=0). No modifications were made to the core dataset, aside from basic file type change to json for (un)packaging with matminer. Reproduced under the Creative Commons 4.0 license, which can be found here: http://creativecommons.org/licenses/by/4.0/.

tholander_nitrides: A challenging data set for quantum machine learning containing a diverse set of 12.8k polymorphs in the Zn-Ti-N, Zn-Zr-N and Zn-Hf-N chemical systems. The phase diagrams of the Ti-Zn-N, Zr-Zn-N, and Hf-Zn-N systems are determined using large-scale high-throughput density functional calculations (DFT-GGA) (PBE). In total 12,815 relaxed structures are shared alongside their energy calculated using the VASP DFT code. The High-Throughput Toolkit was used to manage the calculations. Data adapted and deduplicated from the original data on Zenodo at https://zenodo.org/record/5530535#.YjJ3ZhDMJLQ, published under MIT licence. Collated from separate files of chemical systems and deduplicated according to identical structures matching ht_ids. Prepared in collaboration with Rhys Goodall.

ucsb_thermoelectrics: Database of ~1,100 experimental thermoelectric materials from UCSB aggregated from 108 source publications and personal communications. Downloaded from Citrine. Source UCSB webpage is http://www.mrl.ucsb.edu:8080/datamine/thermoelectric.jsp. See reference for more information on original data aggregation. No duplicate entries are present, but each src may result in multiple measurements of the same materials' properties at different temperatures or conditions.

wolverton_oxides: 4,914 perovskite oxides containing composition data, lattice constants, and formation + vacancy formation energies. All perovskites are of the form ABO3. Adapted from a dataset presented by Emery and Wolverton.

['boltztrap_mp',
 'brgoch_superhard_training',
 'castelli_perovskites',
 'citrine_thermal_conductivity',
 'dielectric_constant',
 'double_perovskites_gap',
 'double_perovskites_gap_lumo',
 'elastic_tensor_2015',
 'expt_formation_enthalpy',
 'expt_formation_enthalpy_kingsbury',
 'expt_gap',
 'expt_gap_kingsbury',
 'flla',
 'glass_binary',
 'glass_binary_v2',
 'glass_ternary_hipt',
 'glass_ternary_landolt',
 'heusler_magnetic',
 'jarvis_dft_2d',
 'jarvis_dft_3d',
 'jarvis_ml_dft_training',
 'm2ax',
 'matbench_dielectric',
 'matbench_expt_gap',
 'matbench_expt_is_metal',
 'matbench_glass',
 'matbench_jdft2d',
 'matbench_log_gvrh',
 'matbench_log_kvrh',
 'matbench_mp_e_form',
 'matbench_mp_gap',
 'matbench_mp_is_metal',
 'matbench_perovskites',
 'matbench_phonons',
 'matbench_steels',
 'mp_all_20181018',
 'mp_nostruct_20181018',
 'phonon_dielectric_mp',
 'piezoelectric_tensor',
 'ricci_boltztrap_mp_tabular',
 'steel_strength',
 'superconductivity2018',
 'tholander_nitrides',
 'ucsb_thermoelectrics',
 'wolverton_oxides']

In [2]:
from matminer.datasets import load_dataset

In [3]:
df= load_dataset("elastic_tensor_2015")

Fetching elastic_tensor_2015.json.gz from https://ndownloader.figshare.com/files/13220603 to /Users/mac/Desktop/naat/anaconda3/lib/python3.12/site-packages/matminer/datasets/elastic_tensor_2015.json.gz

Fetching https://ndownloader.figshare.com/files/13220603 in MB: 1.1182079999999999MB [00:00, 38.33MB/s]

In [4]:
df

,material_id,formula,nsites,space_group,volume,structure,elastic_anisotropy,G_Reuss,G_VRH,G_Voigt,K_Reuss,K_VRH,K_Voigt,poisson_ratio,compliance_tensor,elastic_tensor,elastic_tensor_original,cif,kpoint_density,poscar
0,mp-10003,Nb4CoSi,12,124,194.419802,"[[0.94814328 2.07280467 2.5112 ] Nb, [5.273...",0.030688,96.844535,97.141604,97.438674,194.267623,194.268884,194.270146,0.285701,"[[0.004385293093993, -0.0016070693558990002, -...","[[311.33514638650246, 144.45092552856926, 126....","[[311.33514638650246, 144.45092552856926, 126....",#\#CIF1.1\n###################################...,7000,Nb8 Co2 Si2\n1.0\n6.221780 0.000000 0.000000\n...
1,mp-10010,Al(CoSi)2,5,164,61.987320,"[[0. 0. 0.] Al, [1.96639263 1.13529553 0.75278...",0.266910,93.939650,96.252006,98.564362,173.647763,175.449907,177.252050,0.268105,"[[0.0037715428949660003, -0.000844229828709, -...","[[306.93357350984974, 88.02634955100905, 105.6...","[[306.93357350984974, 88.02634955100905, 105.6...",#\#CIF1.1\n###################################...,7000,Al1 Co2 Si2\n1.0\n3.932782 0.000000 0.000000\n...
2,mp-10015,SiOs,2,221,25.952539,"[[1.480346 1.480346 1.480346] Si, [0. 0. 0.] Os]",0.756489,120.962289,130.112955,139.263621,295.077545,295.077545,295.077545,0.307780,"[[0.0019959391925840004, -0.000433146670736000...","[[569.5291276937579, 157.8517489654999, 157.85...","[[569.5291276937579, 157.8517489654999, 157.85...",#\#CIF1.1\n###################################...,7000,Si1 Os1\n1.0\n2.960692 0.000000 0.000000\n0.00...
3,mp-10021,Ga,4,63,76.721433,"[[0. 1.09045794 0.84078375] Ga, [0. ...",2.376805,12.205989,15.101901,17.997812,49.025963,49.130670,49.235377,0.360593,"[[0.021647143908635, -0.005207263618160001, -0...","[[69.28798774976904, 34.7875015216915, 37.3877...","[[70.13259066665267, 40.60474945058445, 37.387...",#\#CIF1.1\n###################################...,7000,Ga4\n1.0\n2.803229 0.000000 0.000000\n0.000000...
4,mp-10025,SiRu2,12,62,160.300999,"[[1.0094265 4.24771709 2.9955487 ] Si, [3.028...",0.196930,100.110773,101.947798,103.784823,255.055257,256.768081,258.480904,0.324682,"[[0.00410214297725, -0.001272204332729, -0.001...","[[349.3767766177825, 186.67131003104407, 176.4...","[[407.4791016459293, 176.4759188081947, 213.83...",#\#CIF1.1\n###################################...,7000,Si4 Ru8\n1.0\n4.037706 0.000000 0.000000\n0.00...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1176,mp-9961,Ti2CdC,8,194,121.520152,"[[1.55171489 0.89588144 8.41159136] Ti, [-1.88...",2.229538,43.697362,53.329789,62.962216,110.397752,111.788114,113.178476,0.294196,"[[0.0044568832753350005, -0.001136458158149, -...","[[250.07723993082595, 71.61036453717465, 44.31...","[[250.07723993082595, 71.61036453717465, 44.31...",#\#CIF1.1\n###################################...,7000,Ti4 Cd2 C2\n1.0\n3.103427 0.000000 0.000000\n-...
1177,mp-9969,ScSi,8,63,145.392095,"[[0. 8.53417539 0.91740975] Sc, [0. ...",0.635889,66.067578,70.253182,74.438787,101.207608,101.326807,101.446005,0.218412,"[[0.007188192080993001, -0.000983458215036, -0...","[[172.01931871370775, 43.38593006033102, 76.22...","[[172.01931871370775, 43.38593006033102, 76.22...",#\#CIF1.1\n###################################...,7000,Sc4 Si4\n1.0\n3.996960 0.000000 0.000000\n0.00...
1178,mp-9972,YSi,8,63,174.123748,"[[0. 9.084549 0.960921] Y, [0. 1.4...",0.454691,62.326766,65.160458,67.994149,89.416354,89.418161,89.419968,0.206850,"[[0.007749056578454001, -0.001293580144074, -0...","[[159.44792354820547, 42.19645554837514, 66.58...","[[159.44792354820547, 42.19645554837514, 66.58...",#\#CIF1.1\n###################################...,7000,Y4 Si4\n1.0\n4.286685 0.000000 0.000000\n0.000...
1179,mp-998,Al2Cu,12,140,179.147816,"[[5.11035838 2.07486738 0. ] Al, [3.996...",0.735449,37.457129,40.211802,42.966475,99.383115,99.384565,99.386015,0.321738,"[[0.007456839159427001, -0.002592061077082, -0...","[[170.12510286354689, 70.6116049091726, 57.026...","[[170.12510286354689, 70.6116049091726, 57.026...",#\#CIF1.1\n###################################...,7000,Al8 Cu4\n1.0\n6.070982 0.000000 0.000000\n0.00...
1180,mp-21855,VCu3Se4,8,215,180.206796,"[[0. 0. 0.] V, [0. 2.824189 0. ] Cu...",0.205718,20.270037,20.687028,21.104019,35.938660,35.938660,35.938660,0.258523,"[[0.015691632393924, -0.0032083858563950003, -...","[[71.2124153391889, 18.30120539073223, 18.3030...","[[71.2124153391889, 18.30120539073223, 18.3030...",#\#CIF1.1\n###################################...,7000,V1 Cu3 Se4\n1.0\n5.648378 0.000000 0.000000\n0...

In [5]:
import pandas as pd

In [26]:
from mp_api.client import MPRester

In [6]:
df.to_csv("elastic.csv")

In [89]:
mpr=MPRester("JSNhVwG6Nf4t5POzLrhz9pxB3GD6h1xZ")

In [10]:
doc = mpr.materials.insertion_electrodes.search()

Retrieving InsertionElectrodeDoc documents:   0%|          | 0/4351 [00:00<?, ?it/s]

In [16]:
print(mpr.materials.insertion_electrodes.available_fields)

['battery_type', 'battery_id', 'thermo_type', 'battery_formula', 'working_ion', 'num_steps', 'max_voltage_step', 'last_updated', 'framework', 'framework_formula', 'elements', 'nelements', 'chemsys', 'formula_anonymous', 'warnings', 'formula_charge', 'formula_discharge', 'max_delta_volume', 'average_voltage', 'capacity_grav', 'capacity_vol', 'energy_grav', 'energy_vol', 'fracA_charge', 'fracA_discharge', 'stability_charge', 'stability_discharge', 'id_charge', 'id_discharge', 'host_structure', 'adj_pairs', 'material_ids', 'entries_composition_summary', 'electrode_object']

In [17]:
doc

[MPDataDoc<InsertionElectrodeDoc>(
 battery_id='mp-30_Al',
 battery_formula='Al0-2Cu',
 working_ion=Element Al,
 num_steps=1,
 max_voltage_step=0.0,
 last_updated=datetime.datetime(2022, 6, 28, 3, 50, 30, 344000, tzinfo=datetime.timezone.utc),
 framework=Composition('Cu1'),
 framework_formula='Cu',
 elements=[Element Cu],
 nelements=1,
 chemsys='Cu',
 formula_anonymous='A',
 warnings=['More than one working ion per transition metal'],
 formula_charge='Cu',
 formula_discharge='Al2Cu',
 max_delta_volume=3.043399166099431,
 average_voltage=0.08903311500000004,
 capacity_grav=1368.4805523447967,
 capacity_vol=5562.790129820172,
 energy_grav=121.84008639217785,
 energy_vol=495.27253334914457,
 fracA_charge=0.0,
 fracA_discharge=0.6666666666666666,
 stability_charge=0.0,
 stability_discharge=0.0,
 id_charge=MPID(mp-30),
 id_discharge=MPID(mp-985806),
 host_structure=Structure Summary
 Lattice
     abc : 2.56061891665316 2.56061891665316 2.56061891665316
  angles : 60.00000000000001 60.00000000000001 60.00000000000001
  volume : 11.871889639130941
       A : 0.0 1.810631 1.810631
       B : 1.810631 0.0 1.810631
       C : 1.810631 1.810631 0.0
     pbc : True True True
 PeriodicSite: Cu (0.0, 0.0, 0.0) [0.0, 0.0, 0.0],
 adj_pairs=[InsertionVoltagePairDoc(formula_charge='Cu', formula_discharge='Al2Cu', max_delta_volume=3.043399166099431, average_voltage=0.08903311500000004, capacity_grav=1368.4805523447967, capacity_vol=5562.790129820172, energy_grav=121.84008639217785, energy_vol=495.27253334914457, fracA_charge=0.0, fracA_discharge=0.6666666666666666, stability_charge=0.0, stability_discharge=0.0, id_charge=MPID(mp-30), id_discharge=MPID(mp-985806))],
 material_ids=[MPID(mp-30), MPID(mp-985806)],
 entries_composition_summary=EntriesCompositionSummary(all_formulas=['Cu', 'Al2Cu'], all_chemsys=['Al-Cu', 'Cu'], all_formula_anonymous=['A', 'AB2'], all_elements=[Element Al, Element Cu], all_composition_reduced={'Cu': [1.0], 'Al': [2.0]}),
 electrode_object=InsertionElectrode with endpoints at Cu and Al2Cu
 Avg. volt. = 0.08903311500000004 V
 Grav. cap. = 1368.4805523447967 mAh/g
 Vol. cap. = 5562.790129820172,
 fields_not_requested=['battery_type', 'thermo_type']
 ),
 MPDataDoc<InsertionElectrodeDoc>(
 battery_id='mp-1022721_Al',
 battery_formula='Al1-3Cu',
 working_ion=Element Al,
 num_steps=1,
 max_voltage_step=0.0,
 last_updated=datetime.datetime(2022, 6, 28, 3, 50, 30, 344000, tzinfo=datetime.timezone.utc),
 framework=Composition('Cu1'),
 framework_formula='Cu',
 elements=[Element Cu],
 nelements=1,
 chemsys='Cu',
 formula_anonymous='A',
 warnings=['More than one working ion per transition metal'],
 formula_charge='AlCu',
 formula_discharge='Al3Cu',
 max_delta_volume=1.2436527620376623,
 average_voltage=-0.021586344999999934,
 capacity_grav=1112.936545960678,
 capacity_vol=4418.979753458019,
 energy_grav=-24.024232244215476,
 energy_vol=-95.38962150615946,
 fracA_charge=0.5,
 fracA_discharge=0.75,
 stability_charge=0.07406123800000142,
 stability_discharge=0.09624583499999995,
 id_charge=MPID(mp-1022721),
 id_discharge=MPID(mp-1183161),
 host_structure=Structure Summary
 Lattice
     abc : 2.997509 2.997509 2.997509
  angles : 90.0 90.0 90.0
  volume : 26.932798830272144
       A : 2.997509 0.0 0.0
       B : 0.0 2.997509 0.0
       C : 0.0 0.0 2.997509
     pbc : True True True
 PeriodicSite: Cu (1.499, 1.499, 1.499) [0.5, 0.5, 0.5],
 adj_pairs=[InsertionVoltagePairDoc(formula_charge='AlCu', formula_discharge='Al3Cu', max_delta_volume=1.2436527620376623, average_voltage=-0.021586344999999934, capacity_grav=1112.936545960678, capacity_vol=4418.979753458019, energy_grav=-24.024232244215476, energy_vol=-95.38962150615946, fracA_charge=0.5, fracA_discharge=0.75, stability_charge=0.07406123800000142, stability_discharge=0.09624583499999995, id_charge=MPID(mp-1022721), id_discharge=MPID(mp-1183161))],
 material_ids=[MPID(mp-1022721), MPID(mp-1183161)],
 entries_composition_summary=EntriesCompositionSummary(all_formulas=['Al3Cu', 'AlCu'], all_chemsys=['Al-Cu'], all_formula_anonymous=['AB', 'AB3'], all_elements=[Element Al, Element Cu], all_composition_reduced={'Al': [1.0, 3.0], 'Cu': [1.0]}),
 electrode_object=InsertionElectrode with endpoints at AlCu and Al3Cu
 Avg. volt. = -0.021586344999999934 V
 Grav. cap. = 1112.936545960678 mAh/g
 Vol. cap. = 4418.979753458019,
 fields_not_requested=['battery_type', 'thermo_type']
 ),
 MPDataDoc<InsertionElectrodeDoc>(
 battery_id='mp-8637_Al',
 battery_formula='Al0-5Mo',
 working_ion=Element Al,
 num_steps=1,
 max_voltage_step=0.0,
 last_updated=datetime.datetime(2022, 6, 28, 3, 50, 30, 344000, tzinfo=datetime.timezone.utc),
 framework=Composition('Mo1'),
 framework_formula='Mo',
 elements=[Element Mo],
 nelements=1,
 chemsys='Mo',
 formula_anonymous='A',
 warnings=['More than one working ion per transition metal'],
 formula_charge='Mo',
 formula_discharge='Al5Mo',
 max_delta_volume=4.7625742926678125,
 average_voltage=0.1227568450000002,
 capacity_grav=1741.504157810485,
 capacity_vol=7175.701747409025,
 energy_grav=213.7815559671976,
 energy_vol=880.8665071729203,
 fracA_charge=0.0,
 fracA_discharge=0.8333333333333334,
 stability_charge=0.41146009999999933,
 stability_discharge=0.0452119541666649,
 id_charge=MPID(mp-8637),
 id_discharge=MPID(mp-571053),
 host_structure=Structure Summary
 Lattice
     abc : 2.836902506625492 2.836902506625492 2.836902506625492
  angles : 59.99999999999999 59.99999999999999 59.99999999999999
  volume : 16.144263423077767
       A : 0.0 2.005993 2.005993
       B : 2.005993 0.0 2.005993
       C : 2.005993 2.005993 0.0
     pbc : True True True
 PeriodicSite: Mo (0.0, 0.0, 0.0) [0.0, 0.0, 0.0],
 adj_pairs=[InsertionVoltagePairDoc(formula_charge='Mo', formula_discharge='Al5Mo', max_delta_volume=4.7625742926678125, average_voltage=0.1227568450000002, capacity_grav=1741.504157810485, capacity_vol=7175.701747409025, energy_grav=213.7815559671976, energy_vol=880.8665071729203, fracA_charge=0.0, fracA_discharge=0.8333333333333334, stability_charge=0.41146009999999933, stability_discharge=0.0452119541666649, id_charge=MPID(mp-8637), id_discharge=MPID(mp-571053))],
 material_ids=[MPID(mp-8637), MPID(mp-571053)],
 entries_composition_summary=EntriesCompositionSummary(all_formulas=['Al5Mo', 'Mo'], all_chemsys=['Al-Mo', 'Mo'], all_formula_anonymous=['A', 'AB5'], all_elements=[Element Al, Element Mo], all_composition_reduced={'Mo': [1.0], 'Al': [5.0]}),
 electrode_object=InsertionElectrode with endpoints at Mo and Al5Mo
 Avg. volt. = 0.1227568450000002 V
 Grav. cap. = 1741.504157810485 mAh/g
 Vol. cap. = 7175.701747409025,
 fields_not_requested=['battery_type', 'thermo_type']
 ),
 MPDataDoc<InsertionElectrodeDoc>(
 battery_id='mp-129_Al',
 battery_formula='Al0-12Mo',
 working_ion=Element Al,
 num_steps=1,
 max_voltage_step=0.0,
 last_updated=datetime.datetime(2022, 6, 28, 3, 50, 30, 344000, tzinfo=datetime.timezone.utc),
 framework=Composition('Mo1'),
 framework_formula='Mo',
 elements=[Element Mo],
 nelements=1,
 chemsys='Mo',
 formula_anonymous='A',
 warnings=['More than one working ion per transition metal'],
 formula_charge='Mo',
 formula_discharge='Al12Mo',
 max_delta_volume=12.723893064606141,
 average_voltage=0.04312143250000015,
 capacity_grav=2298.8107644274346,
 capacity_vol=7346.232301868708,
 energy_grav=99.12801320853136,
 energy_vol=316.7800603343522,
 fracA_charge=0.0,
 fracA_discharge=0.9230769230769231,
 stability_charge=0.0,
 stability_discharge=0.011445594615390853,
 id_charge=MPID(mp-129),
 id_discharge=MPID(mp-550),
 host_structure=Structure Summary
 Lattice
     abc : 2.743237657484856 2.743237657484856 2.743237657484856
  angles : 109.47122063449069 109.47122063449069 109.47122063449069
  volume : 15.891628753050979
       A : -1.583809 1.583809 1.583809
       B : 1.583809 -1.583809 1.583809
       C : 1.583809 1.583809 -1.583809
     pbc : True True True
 PeriodicSite: Mo (0.0, 0.0, 0.0) [0.0, 0.0, 0.0],
 adj_pairs=[InsertionVoltagePairDoc(formula_charge='Mo', formula_discharge='Al12Mo', max_delta_volume=12.723893064606141, average_voltage=0.04312143250000015, capacity_grav=2298.8107644274346, capacity_vol=7346.232301868708, energy_grav=99.12801320853136, energy_vol=316.7800603343522, fracA_charge=0.0, fracA_discharge=0.9230769230769231, stability_charge=0.0, stability_discharge=0.011445594615390853, id_charge=MPID(mp-129), id_discharge=MPID(mp-550))],
 material_ids=[MPID(mp-129), MPID(mp-550)],
 entries_composition_summary=EntriesCompositionSummary(all_formulas=['Mo', 'Al12Mo'], all_chemsys=['Al-Mo', 'Mo'], all_formula_anonymous=['A', 'AB12'], all_elements=[Element Al, Element Mo], all_composition_reduced={'Mo': [1.0], 'Al': [12.0]}),
 electrode_object=InsertionElectrode with endpoints at Mo and Al12Mo
 Avg. volt. = 0.04312143250000015 V
 Grav. cap. = 2298.8107644274346 mAh/g
 Vol. cap. = 7346.232301868708,
 fields_not_requested=['battery_type', 'thermo_type']
 ),
 MPDataDoc<InsertionElectrodeDoc>(
 battery_id='mp-91_Al',
 battery_formula='Al0-12W',
 working_ion=Element Al,
 num_steps=1,
 max_voltage_step=0.0,
 last_updated=datetime.datetime(2022, 6, 28, 3, 50, 30, 344000, tzinfo=datetime.timezone.utc),
 framework=Composition('W1'),
 framework_formula='W',
 elements=[Element W],
 nelements=1,
 chemsys='W',
 formula_anonymous='A',
 warnings=['More than one working ion per transition metal'],
 formula_charge='W',
 formula_discharge='Al12W',
 max_delta_volume=12.494597710468973,
 average_voltage=0.029234205833333252,
 capacity_grav=1900.7451288330128,
 capacity_vol=7332.71861237705,
 energy_grav=55.566774333009825,
 energy_vol=214.36620523214447,
 fracA_charge=0.0,
 fracA_discharge=0.9230769230769231,
 stability_charge=0.0,
 stability_discharge=0.0,
 id_charge=MPID(mp-91),
 id_discharge=MPID(mp-11227),
 host_structure=Structure Summary
 Lattice
     abc : 2.7603814963781725 2.7603814963781725 2.7603814963781725
  angles : 109.47122063449069 109.47122063449069 109.47122063449069
  volume : 16.191438398643058
       A : -1.593707 1.593707 1.593707
       B : 1.593707 -1.593707 1.593707
       C : 1.593707 1.593707 -1.593707
     pbc : True True True
 PeriodicSite: W (0.0, 0.0, 0.0) [0.0, 0.0, 0.0],
 adj_pairs=[InsertionVoltagePairDoc(formula_charge='W', formula_discharge='Al12W', max_delta_volume=12.494597710468973, average_voltage=0.029234205833333252, capacity_grav=1900.7451288330128, capacity_vol=7332.71861237705, energy_grav=55.566774333009825, energy_vol=214.36620523214447, fracA_charge=0.0, fracA_discharge=0.9230769230769231, stability_charge=0.0, stability_discharge=0.0, id_charge=MPID(mp-91), id_discharge=MPID(mp-11227))],
 material_ids=[MPID(mp-91), MPID(mp-11227)],
 entries_composition_summary=EntriesCompositionSummary(all_formulas=['W', 'Al12W'], all_chemsys=['Al-W', 'W'], all_formula_anonymous=['A', 'AB12'], all_elements=[Element Al, Element W], all_composition_reduced={'W': [1.0], 'Al': [12.0]}),
 electrode_object=InsertionElectrode with endpoints at W and Al12W
 Avg. volt. = 0.029234205833333252 V
 Grav. cap. = 1900.7451288330128 mAh/g
 Vol. cap. = 7332.71861237705,
 fields_not_requested=['battery_type', 'thermo_type']
 ),
 MPDataDoc<InsertionElectrodeDoc>(
 battery_id='mp-1055908_Al',
 battery_formula='Al0-12Mn',
 working_ion=Element Al,
 num_steps=1,
 max_voltage_step=0.0,
 last_updated=datetime.datetime(2022, 6, 28, 3, 50, 30, 344000, tzinfo=datetime.timezone.utc),
 framework=Composition('Mn1'),
 framework_formula='Mn',
 elements=[Element Mn],
 nelements=1,
 chemsys='Mn',
 formula_anonymous='A',
 warnings=['More than one working ion per transition metal'],
 formula_charge='Mn',
 formula_discharge='MnAl12',
 max_delta_volume=18.236156337761482,
 average_voltage=0.03973135916666667,
 capacity_grav=2547.6928001341876,
 capacity_vol=7592.91608289565,
 energy_grav=101.22329768846213,
 energy_vol=301.67687601188686,
 fracA_charge=0.0,
 fracA_discharge=0.9230769230769231,
 stability_charge=0.14546432206896398,
 stability_discharge=0.0,
 id_charge=MPID(mp-1055908),
 id_discharge=MPID(mp-1104165),
 host_structure=Structure Summary
 Lattice
     abc : 2.424386156370309 2.424386156370309 2.424386156370309
  angles : 109.47122063449069 109.47122063449069 109.47122063449069
  volume : 10.969415717032193
       A : -1.39972 1.39972 1.39972
       B : 1.39972 -1.39972 1.39972
       C : 1.39972 1.39972 -1.39972
     pbc : True True True
 PeriodicSite: Mn (0.0, 0.0, 0.0) [0.0, 0.0, 0.0],
 adj_pairs=[InsertionVoltagePairDoc(formula_charge='Mn', formula_discharge='MnAl12', max_delta_volume=18.236156337761482, average_voltage=0.03973135916666667, capacity_grav=2547.6928001341876, capacity_vol=7592.91608289565, energy_grav=101.22329768846213, energy_vol=301.67687601188686, fracA_charge=0.0, fracA_discharge=0.9230769230769231, stability_charge=0.14546432206896398, stability_discharge=0.0, id_charge=MPID(mp-1055908), id_discharge=MPID(mp-1104165))],
 material_ids=[MPID(mp-1055908), MPID(mp-1104165)],
 entries_composition_summary=EntriesCompositionSummary(all_formulas=['Mn', 'MnAl12'], all_chemsys=['Al-Mn', 'Mn'], all_formula_anonymous=['A', 'AB12'], all_elements=[Element Mn, Element Al], all_composition_reduced={'Mn': [1.0], 'Al': [12.0]}),
 electrode_object=InsertionElectrode with endpoints at Mn and MnAl12
 Avg. volt. = 0.03973135916666667 V
 Grav. cap. = 2547.6928001341876 mAh/g
 Vol. cap. = 7592.91608289565,
 fields_not_requested=['battery_type', 'thermo_type']
 ),
 MPDataDoc<InsertionElectrodeDoc>(
 battery_id='mp-2658_Al',
 battery_formula='Al0-1Fe',
 working_ion=Element Al,
 num_steps=1,
 max_voltage_step=0.0,
 last_updated=datetime.datetime(2022, 6, 28, 3, 50, 30, 344000, tzinfo=datetime.timezone.utc),
 framework=Composition('Fe1'),
 framework_formula='Fe',
 elements=[Element Fe],
 nelements=1,
 chemsys='Fe',
 formula_anonymous='A',
 warnings=[],
 formula_charge='Fe',
 formula_discharge='AlFe',
 max_delta_volume=0.7711538538175469,
 average_voltage=0.47172873000000004,
 capacity_grav=970.7570157482313,
 capacity_vol=5622.356217978021,
 energy_grav=457.9339741775032,
 energy_vol=2652.226958314375,
 fracA_charge=0.0,
 fracA_discharge=0.5,
 stability_charge=0.7613994000000002,
 stability_discharge=0.0,
 id_charge=MPID(mp-568345),
 id_discharge=MPID(mp-2658),
 host_structure=Structure Summary
 Lattice
     abc : 2.375663 2.375663 2.375663
  angles : 90.0 90.0 90.0
  volume : 13.407706710345558
       A : 2.375663 0.0 0.0
       B : 0.0 2.375663 0.0
       C : 0.0 0.0 2.375663
     pbc : True True True
 PeriodicSite: Fe (1.188, 1.188, 1.188) [0.5, 0.5, 0.5],
 adj_pairs=[InsertionVoltagePairDoc(formula_charge='Fe', formula_discharge='AlFe', max_delta_volume=0.7711538538175469, average_voltage=0.47172873000000004, capacity_grav=970.7570157482313, capacity_vol=5622.356217978021, energy_grav=457.9339741775032, energy_vol=2652.226958314375, fracA_charge=0.0, fracA_discharge=0.5, stability_charge=0.7613994000000002, stability_discharge=0.0, id_charge=MPID(mp-568345), id_discharge=MPID(mp-2658))],
 material_ids=[MPID(mp-568345), MPID(mp-2658)],
 entries_composition_summary=EntriesCompositionSummary(all_formulas=['Fe', 'AlFe'], all_chemsys=['Al-Fe', 'Fe'], all_formula_anonymous=['A', 'AB'], all_elements=[Element Al, Element Fe], all_composition_reduced={'Fe': [1.0], 'Al': [1.0]}),
 electrode_object=InsertionElectrode with endpoints at Fe and AlFe
 Avg. volt. = 0.47172873000000004 V
 Grav. cap. = 970.7570157482313 mAh/g
 Vol. cap. = 5622.356217978021,
 fields_not_requested=['battery_type', 'thermo_type']
 ),
 MPDataDoc<InsertionElectrodeDoc>(
 battery_id='mp-16722_Al',
 battery_formula='Al1-10.25V',
 working_ion=Element Al,
 num_steps=1,
 max_voltage_step=0.0,
 last_updated=datetime.datetime(2022, 6, 28, 3, 50, 30, 344000, tzinfo=datetime.timezone.utc),
 framework=Composition('V1'),
 framework_formula='V',
 elements=[Element V],
 nelements=1,
 chemsys='V',
 formula_anonymous='A',
 warnings=['More than one working ion per transition metal'],
 formula_charge='Al10V',
 formula_discharge='Al41V4',
 max_delta_volume=0.0027108033523548514,
 average_voltage=-0.01558272333334069,
 capacity_grav=61.37701219331353,
 capacity_vol=176.41513079509815,
 energy_grav=-0.9564210000354828,
 energy_vol=-2.7490281749951255,
 fracA_charge=0.9090909090909091,
 fracA_discharge=0.9111111111111111,
 stability_charge=0.01180966318181742,
 stability_discharge=0.01258607444444415,
 id_charge=MPID(mp-16722),
 id_discharge=MPID(mp-1229052),
 host_structure=Structure Summary
 Lattice
     abc : 10.219842592760418 10.219842592760418 10.219842592760418
  angles : 59.99999999999999 59.99999999999999 59.99999999999999
  volume : 754.7752011128636
       A : 0.0 7.22652 7.22652
       B : 7.22652 0.0 7.22652
       C : 7.22652 7.22652 0.0
     pbc : True True True
 PeriodicSite: V (1.807, 1.807, 1.807) [0.125, 0.125, 0.125]
 PeriodicSite: V (1.807, 5.42, 5.42) [0.625, 0.125, 0.125]
 PeriodicSite: V (5.42, 1.807, 5.42) [0.125, 0.625, 0.125]
 PeriodicSite: V (5.42, 5.42, 1.807) [0.125, 0.125, 0.625],
 adj_pairs=[InsertionVoltagePairDoc(formula_charge='Al10V', formula_discharge='Al41V4', max_delta_volume=0.0027108033523548514, average_voltage=-0.01558272333334069, capacity_grav=61.37701219331353, capacity_vol=176.41513079509815, energy_grav=-0.9564210000354828, energy_vol=-2.7490281749951255, fracA_charge=0.9090909090909091, fracA_discharge=0.9111111111111111, stability_charge=0.01180966318181742, stability_discharge=0.01258607444444415, id_charge=MPID(mp-16722), id_discharge=MPID(mp-1229052))],
 material_ids=[MPID(mp-16722), MPID(mp-1229052)],
 entries_composition_summary=EntriesCompositionSummary(all_formulas=['Al41V4', 'Al10V'], all_chemsys=['Al-V'], all_formula_anonymous=['AB10', 'A4B41'], all_elements=[Element Al, Element V], all_composition_reduced={'Al': [41.0, 10.0], 'V': [1.0, 4.0]}),
 electrode_object=InsertionElectrode with endpoints at Al10V and Al41V4
 Avg. volt. = -0.01558272333334069 V
 Grav. cap. = 61.37701219331353 mAh/g
 Vol. cap. = 176.41513079509815,
 fields_not_requested=['battery_type', 'thermo_type']
 ),
 MPDataDoc<InsertionElectrodeDoc>(
 battery_id='mp-998981_Al',
 battery_formula='Al1-3Ti',
 working_ion=Element Al,
 num_steps=1,
 max_voltage_step=0.0,
 last_updated=datetime.datetime(2022, 6, 28, 3, 50, 30, 344000, tzinfo=datetime.timezone.utc),
 framework=Composition('Ti1'),
 framework_formula='Ti',
 elements=[Element Ti],
 nelements=1,
 chemsys='Ti',
 formula_anonymous='A',
 warnings=['More than one working ion per transition metal'],
 formula_charge='TiAl',
 formula_discharge='TiAl3',
 max_delta_volume=0.9562924420330603,
 average_voltage=0.16024498499999998,
 capacity_grav=1248.4036154151197,
 capacity_vol=4248.421059693514,
 energy_grav=200.0504186261416,
 energy_vol=680.7881689842711,
 fracA_charge=0.5,
 fracA_discharge=0.75,
 stability_charge=0.14159115499999952,
 stability_discharge=0.0244962150000001,
 id_charge=MPID(mp-1061123),
 id_discharge=MPID(mp-998981),
 host_structure=Structure Summary
 Lattice
     abc : 3.179064 3.179064 3.179064
  angles : 90.0 90.0 90.0
  volume : 32.129044737935814
       A : 3.179064 0.0 0.0
       B : 0.0 3.179064 0.0
       C : 0.0 0.0 3.179064
     pbc : True True True
 PeriodicSite: Ti (0.0, 0.0, 0.0) [0.0, 0.0, 0.0],
 adj_pairs=[InsertionVoltagePairDoc(formula_charge='TiAl', formula_discharge='TiAl3', max_delta_volume=0.9562924420330603, average_voltage=0.16024498499999998, capacity_grav=1248.4036154151197, capacity_vol=4248.421059693514, energy_grav=200.0504186261416, energy_vol=680.7881689842711, fracA_charge=0.5, fracA_discharge=0.75, stability_charge=0.14159115499999952, stability_discharge=0.0244962150000001, id_charge=MPID(mp-1061123), id_discharge=MPID(mp-998981))],
 material_ids=[MPID(mp-1061123), MPID(mp-998981)],
 entries_composition_summary=EntriesCompositionSummary(all_formulas=['TiAl3', 'TiAl'], all_chemsys=['Al-Ti'], all_formula_anonymous=['AB', 'AB3'], all_elements=[Element Ti, Element Al], all_composition_reduced={'Ti': [1.0], 'Al': [1.0, 3.0]}),

In [20]:

data = []
for docs in doc:
    row = {
        "battery_id": docs.battery_id,
        "battery_formula": docs.battery_formula,
        "nelements": docs.nelements,
        "working_ion": docs.working_ion,
        "max_voltage_step": docs.max_voltage_step,
        "average_voltage (V)": docs.average_voltage,
        "max_delta_volume (%)": docs.max_delta_volume,
        "average_voltage (V)": docs.average_voltage,
        "capacity_grav (mAh/g)": docs.capacity_grav,
        "capacity_vol (mAh/cc)": docs.capacity_vol,
        "energy_grav (Wh/kg)": docs.energy_grav,
        "energy_vol (Wh/l)": docs.energy_vol,
        "stability_charge (MeV/atom)": docs.stability_charge,
        "stability_discharge (MeV/atom)": docs.stability_discharge,
    }
    data.append(row)
# we can add any available features
# Creating a pandas DataFrame
df1 = pd.DataFrame(data)

In [21]:
df1

,battery_id,battery_formula,nelements,working_ion,max_voltage_step,average_voltage (V),max_delta_volume (%),capacity_grav (mAh/g),capacity_vol (mAh/cc),energy_grav (Wh/kg),energy_vol (Wh/l),stability_charge (MeV/atom),stability_discharge (MeV/atom)
0,mp-30_Al,Al0-2Cu,1,Al,0.000000,0.089033,3.043399,1368.480552,5562.790130,121.840086,495.272533,0.000000,0.000000
1,mp-1022721_Al,Al1-3Cu,1,Al,0.000000,-0.021586,1.243653,1112.936546,4418.979753,-24.024232,-95.389622,0.074061,0.096246
2,mp-8637_Al,Al0-5Mo,1,Al,0.000000,0.122757,4.762574,1741.504158,7175.701747,213.781556,880.866507,0.411460,0.045212
3,mp-129_Al,Al0-12Mo,1,Al,0.000000,0.043121,12.723893,2298.810764,7346.232302,99.128013,316.780060,0.000000,0.011446
4,mp-91_Al,Al0-12W,1,Al,0.000000,0.029234,12.494598,1900.745129,7332.718612,55.566774,214.366205,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4346,mp-1306381_Li,Li2-3MnCo3O8,3,Li,0.000000,3.193511,0.015792,70.427199,313.095570,224.910062,999.874271,0.089548,0.098319
4347,mp-753606_Li,Li0-2MnCoO4,3,Li,1.570665,3.416358,0.128945,279.544863,1186.839362,955.025295,4054.668004,0.056537,0.062007
4348,mp-754108_Li,Li0-4MnCo3O8,3,Li,1.617985,3.390423,0.108876,276.662714,1202.483175,938.003662,4076.926761,0.021501,0.076030
4349,mp-554804_Li,Li0.5-1.75MnP2O7,3,Li,0.819649,4.803113,0.052117,138.995614,408.409222,667.611624,1961.635595,0.097221,0.007304
4350,mp-27013_Li,Li3-9V3P8O29,3,Li,1.958530,4.123430,0.043618,173.459983,457.176531,715.250132,1885.135512,0.038883,0.000164

In [22]:
df1.to_csv("battery.csv")

In [28]:
dic = mpr.materials.piezoelectric.search()

Retrieving PiezoelectricDoc documents:   0%|          | 0/3299 [00:00<?, ?it/s]

In [29]:
print(mpr.materials.piezoelectric.available_fields)

['builder_meta', 'nsites', 'elements', 'nelements', 'composition', 'composition_reduced', 'formula_pretty', 'formula_anonymous', 'chemsys', 'volume', 'density', 'density_atomic', 'symmetry', 'property_name', 'material_id', 'deprecated', 'deprecation_reasons', 'last_updated', 'origins', 'warnings', 'total', 'ionic', 'electronic', 'e_ij_max', 'max_direction', 'strain_for_max']

In [33]:
data1=[]
for doc in dic:
    column={'material_id':doc.material_id,
            'nsites':doc.nsites,
           'elements':doc.elements,
           'nelements':doc.nelements,
           'composition':doc.composition,
           'formula_pretty':doc.formula_pretty,
           'chemsys:':doc.chemsys,
           'volume':doc.volume,
           'ionic':doc.ionic,
           'electronic':doc.electronic,
           'composition_reduced':doc.composition_reduced,
           'density':doc.density}
    data1.append(column)
sf=pd.DataFrame(data1)

In [34]:
sf

,material_id,nsites,elements,nelements,composition,formula_pretty,chemsys:,volume,ionic,electronic,composition_reduced,density
0,mp-14,3,[Se],1,(Se),Se,Se,89.329027,"[[-0.13648001925232553, 0.1364799936201212, 0....","[[-0.2966900417908433, 0.2966899860697215, 0.0...",(Se),4.403367
1,mp-19,3,[Te],1,(Te),Te,Te,93.888296,"[[-0.925467087473412, 0.9254676307405351, 0.0,...","[[-0.5816297457823855, 0.5816300872103226, 0.0...",(Te),6.770326
2,mp-864900,58,[Hg],1,(Hg),Hg,Hg,1793.649248,"[[0.0, 0.0, 0.0, 0.028360000000000007, 0.0, 0....","[[0.0, 0.0, 0.0, 0.012790000000000003, 0.0, 0....",(Hg),10.770822
3,mp-971661,46,[Si],1,(Si),Si,Si,1030.760113,"[[0.0, 0.0, 0.0, -0.003149999999999998, 0.0, 0...","[[0.0, 0.0, 0.0, 0.005069999999999996, 0.0, 0....",(Si),2.081285
4,mp-567313,3,[Te],1,(Te),Te,Te,104.552874,"[[-0.7084551031394173, 0.7084549655522185, 0.0...","[[-0.5245500764036144, 0.5245499745321263, 0.0...",(Te),6.079741
...,...,...,...,...,...,...,...,...,...,...,...,...
3294,mp-757130,26,"[C, Co, Cr, Li, O, P]",6,"(Li, Cr, Co, P, C, O)",Li6CrCoP2(CO7)2,C-Co-Cr-Li-O-P,276.046321,"[[1.18501, 0.26211, -0.23847, 0.0, 0.53563, 0....","[[0.01718, 0.00237, -0.00392, 0.0, -0.00253, 0...","(Li, Cr, Co, P, C, O)",2.782355
3295,mp-757146,26,"[C, Fe, Li, Mn, O, P]",6,"(Li, Mn, Fe, P, C, O)",Li6MnFeP2(CO7)2,C-Fe-Li-Mn-O-P,279.358038,"[[0.01689, 0.01798, -0.02344, 0.0, 0.05655, 0....","[[0.0, 0.0, 0.01528, 0.0, 0.00314, 0.0], [0.0,...","(Li, Mn, Fe, P, C, O)",2.748501
3296,mp-42805,38,"[Cl, Cu, H, K, N, O]",6,"(K, Cu, H, N, Cl, O)",KCu2H20N3(Cl2O)4,Cl-Cu-H-K-N-O,472.343334,"[[0.0, 0.0, 0.0, 0.0034000000000000002, 0.0047...","[[0.0, 0.0, 0.0, -0.00172, 0.00676, 0.0], [0.0...","(K, Cu, H, N, Cl, O)",2.024915
3297,mp-42583,46,"[Al, Be, Cl, Na, O, Si]",6,"(Na, Be, Al, Si, Cl, O)",Na8BeAl4Si7(ClO12)2,Al-Be-Cl-Na-O-Si,729.664057,"[[0.0, 0.0, 0.0, -0.49967, -0.0094449999999999...","[[0.0, 0.0, 0.0, 0.17165, -0.00393, 0.0], [0.0...","(Na, Be, Al, Si, Cl, O)",2.167311
3298,mp-23151,46,"[Al, Be, Cl, Na, O, Si]",6,"(Na, Be, Al, Si, Cl, O)",Na4BeAlSi4ClO12,Al-Be-Cl-Na-O-Si,683.049277,"[[0.0, 0.0, 0.0, -0.29692999999999997, -0.0750...","[[0.0, 0.0, 0.0, 0.13542, 0.00297, 0.0], [0.0,...","(Na, Be, Al, Si, Cl, O)",2.274218

In [35]:
sf.to_csv('piezoelectric.csv')

In [66]:
df_mp= pd.read_csv('piezoelectric.csv')

In [45]:
df_mp.head()

,Unnamed: 0,material_id,nsites,elements,nelements,composition,formula_pretty,chemsys:,volume,ionic,electronic,composition_reduced,density
0,0,mp-14,3,[Element Se],1,Se3,Se,Se,89.329027,"[[-0.13648001925232553, 0.1364799936201212, 0....","[[-0.2966900417908433, 0.2966899860697215, 0.0...",Se1,4.403367
1,1,mp-19,3,[Element Te],1,Te3,Te,Te,93.888296,"[[-0.925467087473412, 0.9254676307405351, 0.0,...","[[-0.5816297457823855, 0.5816300872103226, 0.0...",Te1,6.770326
2,2,mp-864900,58,[Element Hg],1,Hg58,Hg,Hg,1793.649248,"[[0.0, 0.0, 0.0, 0.028360000000000007, 0.0, 0....","[[0.0, 0.0, 0.0, 0.012790000000000003, 0.0, 0....",Hg1,10.770822
3,3,mp-971661,46,[Element Si],1,Si46,Si,Si,1030.760113,"[[0.0, 0.0, 0.0, -0.003149999999999998, 0.0, 0...","[[0.0, 0.0, 0.0, 0.005069999999999996, 0.0, 0....",Si1,2.081285
4,4,mp-567313,3,[Element Te],1,Te3,Te,Te,104.552874,"[[-0.7084551031394173, 0.7084549655522185, 0.0...","[[-0.5245500764036144, 0.5245499745321263, 0.0...",Te1,6.079741

In [73]:
#df_mp= pd.read_csv("battery.csv")
import numpy as np

In [63]:
from matminer.featurizers.composition import ElementProperty
from pymatgen.core import Composition

In [80]:
from pymatgen.core.periodic_table import Element
dataset= Element

In [78]:
df_mp["composition"] = df_mp['formula_pretty'].map(lambda x: Composition(x))

In [69]:
df_mp['vpa'] = df_mp['volume']/df_mp['nsites']

In [82]:
descriptors = ['row', 'group', 'atomic_mass',
               'atomic_radius', 'boiling_point', 'melting_point', 'X']
stats = ["mean", "std_dev"]

ep = ElementProperty(data_source=dataset, features=descriptors, stats=stats)
df_mp = ep.featurize_dataframe(df_mp, "composition",ignore_errors=True)

ElementProperty:   0%|          | 0/3299 [00:00<?, ?it/s]

In [84]:
df_mp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3299 entries, 0 to 3298
Data columns (total 28 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Unnamed: 0                      3299 non-null   int64
 1   material_id                     3299 non-null   object
 2   nsites                          3299 non-null   int64
 3   elements                        3299 non-null   object
 4   nelements                       3299 non-null   int64
 5   composition                     3299 non-null   object
 6   formula_pretty                  3299 non-null   object
 7   chemsys:                        3299 non-null   object
 8   volume                          3299 non-null   float64
 9   ionic                           3299 non-null   object
 10  electronic                      3299 non-null   object
 11  composition_reduced             3299 non-null   object
 12  density                         3299 non-null   float64
 13  vpa                             3299 non-null   float64
 14  EnumType mean row               0 non-null      float64
 15  EnumType std_dev row            0 non-null      float64
 16  EnumType mean group             0 non-null      float64
 17  EnumType std_dev group          0 non-null      float64
 18  EnumType mean atomic_mass       0 non-null      float64
 19  EnumType std_dev atomic_mass    0 non-null      float64
 20  EnumType mean atomic_radius     0 non-null      float64
 21  EnumType std_dev atomic_radius  0 non-null      float64
 22  EnumType mean boiling_point     0 non-null      float64
 23  EnumType std_dev boiling_point  0 non-null      float64
 24  EnumType mean melting_point     0 non-null      float64
 25  EnumType std_dev melting_point  0 non-null      float64
 26  EnumType mean X                 0 non-null      float64
 27  EnumType std_dev X              0 non-null      float64
dtypes: float64(17), int64(3), object(8)
memory usage: 721.8+ KB

In [85]:
df_mp = df_mp.dropna()

In [86]:
df_mp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 28 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Unnamed: 0                      0 non-null      int64
 1   material_id                     0 non-null      object
 2   nsites                          0 non-null      int64
 3   elements                        0 non-null      object
 4   nelements                       0 non-null      int64
 5   composition                     0 non-null      object
 6   formula_pretty                  0 non-null      object
 7   chemsys:                        0 non-null      object
 8   volume                          0 non-null      float64
 9   ionic                           0 non-null      object
 10  electronic                      0 non-null      object
 11  composition_reduced             0 non-null      object
 12  density                         0 non-null      float64
 13  vpa                             0 non-null      float64
 14  EnumType mean row               0 non-null      float64
 15  EnumType std_dev row            0 non-null      float64
 16  EnumType mean group             0 non-null      float64
 17  EnumType std_dev group          0 non-null      float64
 18  EnumType mean atomic_mass       0 non-null      float64
 19  EnumType std_dev atomic_mass    0 non-null      float64
 20  EnumType mean atomic_radius     0 non-null      float64
 21  EnumType std_dev atomic_radius  0 non-null      float64
 22  EnumType mean boiling_point     0 non-null      float64
 23  EnumType std_dev boiling_point  0 non-null      float64
 24  EnumType mean melting_point     0 non-null      float64
 25  EnumType std_dev melting_point  0 non-null      float64
 26  EnumType mean X                 0 non-null      float64
 27  EnumType std_dev X              0 non-null      float64
dtypes: float64(17), int64(3), object(8)
memory usage: 0.0+ bytes

In [88]:
df_mp

Empty DataFrame
Columns: [Unnamed: 0, material_id, nsites, elements, nelements, composition, formula_pretty, chemsys:, volume, ionic, electronic, composition_reduced, density, vpa, EnumType mean row, EnumType std_dev row, EnumType mean group, EnumType std_dev group, EnumType mean atomic_mass, EnumType std_dev atomic_mass, EnumType mean atomic_radius, EnumType std_dev atomic_radius, EnumType mean boiling_point, EnumType std_dev boiling_point, EnumType mean melting_point, EnumType std_dev melting_point, EnumType mean X, EnumType std_dev X]
Index: []

[0 rows x 28 columns]

In [102]:
docm = mpr.materials.elasticity.search()

Retrieving ElasticityDoc documents:   0%|          | 0/12392 [00:00<?, ?it/s]

In [98]:
print(mpr.materials.elasticity.available_fields)

['builder_meta', 'nsites', 'elements', 'nelements', 'composition', 'composition_reduced', 'formula_pretty', 'formula_anonymous', 'chemsys', 'volume', 'density', 'density_atomic', 'symmetry', 'property_name', 'material_id', 'deprecated', 'deprecation_reasons', 'last_updated', 'origins', 'warnings', 'structure', 'order', 'elastic_tensor', 'compliance_tensor', 'bulk_modulus', 'shear_modulus', 'sound_velocity', 'thermal_conductivity', 'young_modulus', 'universal_anisotropy', 'homogeneous_poisson', 'debye_temperature', 'fitting_data', 'fitting_method', 'state']

In [103]:
data2 = []
for doc in docm:
    column = {
        'builder_meta': doc.builder_meta,
        'nsites': doc.nsites,
        'elements': doc.elements,
        'nelements': doc.nelements,
        'composition': doc.composition,
        'composition_reduced': doc.composition_reduced,
        'formula_pretty': doc.formula_pretty,
        'formula_anonymous': doc.formula_anonymous,
        'chemsys': doc.chemsys,
        'volume': doc.volume,
        'density': doc.density,
        'density_atomic': doc.density_atomic,
        'symmetry': doc.symmetry,
        'property_name': doc.property_name,
        'material_id': doc.material_id,
        'deprecated': doc.deprecated,
        'deprecation_reasons': doc.deprecation_reasons,
        'last_updated': doc.last_updated,
        'origins': doc.origins,
        'warnings': doc.warnings,
        'structure': doc.structure,
        'order': doc.order,
        'elastic_tensor': doc.elastic_tensor,
        'compliance_tensor': doc.compliance_tensor,
        'bulk_modulus': doc.bulk_modulus,
        'shear_modulus': doc.shear_modulus,
        'sound_velocity': doc.sound_velocity,
        'thermal_conductivity': doc.thermal_conductivity,
        'young_modulus': doc.young_modulus,
        'universal_anisotropy': doc.universal_anisotropy,
        'homogeneous_poisson': doc.homogeneous_poisson,
        'debye_temperature': doc.debye_temperature,
        'fitting_data': doc.fitting_data,
        'fitting_method': doc.fitting_method,
        'state': doc.state
    }
    data1.append(column)

# Create the DataFrame
sf = pd.DataFrame(data2)

In [107]:
sf.head()

Empty DataFrame
Columns: []
Index: []

In [105]:
data2

[]